version: '3.8'

services:
  web:
    build: ./server
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@localhost:5432/safarsaathi
    volumes:
      - .:/app

volumes: {}
