version: '3.8'

services:
  web:
    build: ./server
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/safarsaathi
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: safarsaathi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: safarsaathi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
